Repository woowacourse-teams/2024-cruru, pull requests merged in 2024-07, with the labels that each got.

#18 feat: Github Action을 이용한 CI 기능 구현
  .github/issue-branch.yml
  .github/workflows/issue-branch-pr-automation.yml
  .github/workflows/review-request-slack-mention.yml
  .github/workflows/reviewers.json
Labels: chore, common

#20 chore: FE 개발환경을 FE 메인 브랜치에 반영
  .eslintrc.json
  .gitignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  index.html
  jest.config.js
  package-lock.json
  package.json
  panda.config.ts
  postcss.config.cjs
  setupTests.ts
  src/App.tsx
  src/assets/images/cat.svg
  src/components/Button/Button.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/test.tsx
  src/custom.d.ts
  src/main.tsx
  tsconfig.json
  webpack.config.js
  webpack.dev.js
  webpack.prod.js
Labels: style, chore, frontend

#36 chore: 스타일링 도구를 emotion으로 대체
  .eslintrc.json
  .github/ISSUE_TEMPLATE/backend-chore-request.md
  .github/ISSUE_TEMPLATE/backend-feature-request.md
  .github/ISSUE_TEMPLATE/backend-fix-request.md
  .github/ISSUE_TEMPLATE/backend-refactor-request.md
  .github/ISSUE_TEMPLATE/backend-test-request.md
  .github/ISSUE_TEMPLATE/frontend-chore-request.md
  .github/ISSUE_TEMPLATE/frontend-feature-request.md
  .github/ISSUE_TEMPLATE/frontend-fix-request.md
  .github/ISSUE_TEMPLATE/frontend-refactor-request.md
  .github/ISSUE_TEMPLATE/frontend-style-request.md
  .github/ISSUE_TEMPLATE/frontend-test-request.md
  .github/issue-branch.yml
  .github/workflows/issue-branch-pr-automation.yml
  .github/workflows/review-request-slack-mention.yml
  .github/workflows/reviewers.json
  package-lock.json
  package.json
Labels: style, chore, frontend

#45 fix-be: updateApplicantProcess 오류 수정
  src/main/java/com/cruru/applicant/service/ApplicantService.java
  src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
Labels: fix, backend

#48 be-refactor: 코드 포맷팅
  src/main/java/com/cruru/BaseEntity.java
  src/main/java/com/cruru/advice/BadRequestException.java
  src/main/java/com/cruru/advice/ForbiddenException.java
  src/main/java/com/cruru/advice/InternalServerException.java
  src/main/java/com/cruru/advice/NonAuthorizedException.java
  src/main/java/com/cruru/advice/NotFoundException.java
  src/main/java/com/cruru/applicant/controller/dto/ApplicantMoveRequest.java
  src/main/java/com/cruru/applicant/controller/dto/DashboardApplicantDto.java
  src/main/java/com/cruru/applicant/domain/Applicant.java
  src/main/java/com/cruru/applicant/domain/repository/ApplicantRepository.java
  src/main/java/com/cruru/club/domain/Club.java
  src/main/java/com/cruru/club/domain/repository/ClubRepository.java
  src/main/java/com/cruru/config/JpaAuditingConfig.java
  src/main/java/com/cruru/dashboard/domain/Dashboard.java
  src/main/java/com/cruru/dashboard/domain/repository/DashboardRepository.java
  src/main/java/com/cruru/member/controller/dto/MemberCreateResponse.java
  src/main/java/com/cruru/member/domain/Member.java
  src/main/java/com/cruru/member/domain/repository/MemberRepository.java
  src/main/java/com/cruru/process/controller/ProcessController.java
  src/main/java/com/cruru/process/controller/dto/ProcessCreateRequest.java
  src/main/java/com/cruru/process/controller/dto/ProcessResponse.java
  src/main/java/com/cruru/process/controller/dto/ProcessesResponse.java
  src/main/java/com/cruru/process/domain/Process.java
  src/main/java/com/cruru/process/domain/repository/ProcessRepository.java
  src/main/java/com/cruru/process/service/ProcessService.java
  src/main/java/com/cruru/question/domain/DescriptiveQuestion.java
  src/test/java/com/cruru/member/domain/repository/MemberRepositoryTest.java
  src/test/java/com/cruru/process/domain/repository/ProcessRepositoryTest.java
  src/test/java/com/cruru/process/service/ProcessServiceTest.java
Labels: refactor, backend

#126 feat-fe: 지원자 기본정보 상세 (모달 내부 왼쪽 부분) _ 02
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/applicant.ts
  frontend/src/components/applicantModal/ApplicantBaseDetail/ApplicantBaseDetail.stories.tsx
  frontend/src/components/applicantModal/ApplicantBaseDetail/index.tsx
  frontend/src/components/applicantModal/ApplicantBaseDetail/style.ts
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/style.ts
  frontend/src/components/common/Dropdown/index.tsx
  frontend/src/components/common/Dropdown/style.ts
  frontend/src/components/dashboard/ProcessColumn/index.tsx
  frontend/src/hooks/queryKeys.ts
  frontend/src/hooks/useApplicant/index.ts
  frontend/src/hooks/useProcess/index.ts
  frontend/src/hooks/useSpecificApplicant/index.ts
  frontend/src/mocks/handlers/applicantHandlers.ts
  frontend/src/mocks/processMockData.json
  frontend/src/mocks/specificApplicant.json
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/types.ts
  frontend/src/types/applicant.ts
  frontend/src/types/common.ts
Labels: feature, frontend
